insall phalcon form ondrej

diff --git a/phalcons b/phalcons
--- a/phalcons
+++ b/phalcons
@@ -10,7 +10,7 @@ case "${UNAMEOUT}" in
 esac
 
 if [ "$MACHINE" == "UNKNOWN" ]; then
-    echo "Unsupported operating system [$(uname -s)]. Laravel Sail supports macOS, Linux, and Windows (WSL2)." >&2
+    echo "Unsupported operating system [$(uname -s)]. Laravel Phalcon supports macOS, Linux, and Windows (WSL2)." >&2
 
     exit 1
 fi
@@ -30,7 +30,7 @@ fi
 
 # Function that prints the available commands...
 function display_help {
-    echo "Laravel Sail"
+    echo "Laravel Phalcon"
     echo
     echo "${YELLOW}Usage:${NC}" >&2
     echo "  phalcons COMMAND [options] [arguments]"
@@ -44,8 +44,8 @@ function display_help {
     echo "  ${GREEN}phalcons restart${NC}   Restart the application"
     echo "  ${GREEN}phalcons ps${NC}        Display the status of all containers"
     echo
-    echo "${YELLOW}Artisan Commands:${NC}"
-    echo "  ${GREEN}phalcons phalcon ...${NC}          Run an Artisan command"
+    echo "${YELLOW}Phalcon Commands:${NC}"
+    echo "  ${GREEN}phalcons phalcon ...${NC}          Run an Phalcon command"
     echo "  ${GREEN}phalcons phalcon queue:work${NC}"
     echo
     echo "${YELLOW}PHP Commands:${NC}"
@@ -76,11 +76,11 @@ function display_help {
     echo "  ${GREEN}phalcons redis${NC}     Start a Redis CLI session within the 'redis' container"
     echo
     echo "${YELLOW}Debugging:${NC}"
-    echo "  ${GREEN}phalcons debug ...${NC}          Run an Artisan command in debug mode"
+    echo "  ${GREEN}phalcons debug ...${NC}          Run an Phalcon command in debug mode"
     echo "  ${GREEN}phalcons debug queue:work${NC}"
     echo
     echo "${YELLOW}Running Tests:${NC}"
-    echo "  ${GREEN}phalcons test${NC}          Run the PHPUnit tests via the Artisan test command"
+    echo "  ${GREEN}phalcons test${NC}          Run the PHPUnit tests via the Phalcon test command"
     echo "  ${GREEN}phalcons phpunit ...${NC}   Run PHPUnit"
     echo "  ${GREEN}phalcons pest ...${NC}      Run Pest"
     echo "  ${GREEN}phalcons pint ...${NC}      Run Pint"
@@ -101,8 +101,8 @@ function display_help {
     echo "  ${GREEN}phalcons bin ...${NC}   Run Composer binary scripts from the vendor/bin directory"
     echo
     echo "${YELLOW}Customization:${NC}"
-    echo "  ${GREEN}phalcons phalcon phalcons:publish${NC}   Publish the Sail configuration files"
-    echo "  ${GREEN}phalcons build --no-cache${NC}       Rebuild all of the Sail containers"
+    echo "  ${GREEN}phalcons phalcon phalcons:publish${NC}   Publish the Phalcon configuration files"
+    echo "  ${GREEN}phalcons build --no-cache${NC}       Rebuild all of the Phalcon containers"
 
     exit 1
 }
@@ -137,11 +137,11 @@ export SAIL_SHARE_SERVER_PORT=${SAIL_SHARE_SERVER_PORT:-8080}
 export SAIL_SHARE_SUBDOMAIN=${SAIL_SHARE_SUBDOMAIN:-""}
 export SAIL_SHARE_DOMAIN=${SAIL_SHARE_DOMAIN:-""}
 
-# Function that outputs Sail is not running...
+# Function that outputs Phalcon is not running...
 function phalcons_is_not_running {
-    echo "${BOLD}Sail is not running.${NC}" >&2
+    echo "${BOLD}Phalcon is not running.${NC}" >&2
     echo "" >&2
-    echo "${BOLD}You may Sail using the following commands:${NC} './vendor/bin/phalcons up' or './vendor/bin/phalcons up -d'" >&2
+    echo "${BOLD}You may Phalcon using the following commands:${NC} './vendor/bin/phalcons up' or './vendor/bin/phalcons up -d'" >&2
 
     exit 1
 }
@@ -179,9 +179,9 @@ if [ -z "$SAIL_SKIP_CHECKS" ]; then
         exit 1
     fi
 
-    # Determine if Sail is currently up...
+    # Determine if Phalcon is currently up...
     if "${DOCKER_COMPOSE[@]}" ps "$APP_SERVICE" 2>&1 | grep 'Exit\|exited'; then
-        echo "${BOLD}Shutting down old Sail processes...${NC}" >&2
+        echo "${BOLD}Shutting down old Phalcon processes...${NC}" >&2
 
         "${DOCKER_COMPOSE[@]}" down > /dev/null 2>&1
 
@@ -241,7 +241,7 @@ elif [ "$1" == "composer" ]; then
         phalcons_is_not_running
     fi
 
-# Proxy Artisan commands to the "phalcon" binary on the application container...
+# Proxy Phalcon commands to the "phalcon" binary on the application container...
 elif [ "$1" == "phalcon" ] || [ "$1" == "art" ]; then
     shift 1
 
@@ -265,7 +265,7 @@ elif [ "$1" == "debug" ]; then
         phalcons_is_not_running
     fi
 
-# Proxy the "test" command to the "phalcon test" Artisan command...
+# Proxy the "test" command to the "phalcon test" Phalcon command...
 elif [ "$1" == "test" ]; then
     shift 1
 
@@ -313,7 +313,7 @@ elif [ "$1" == "pint" ]; then
         phalcons_is_not_running
     fi
 
-# Proxy the "dusk" command to the "phalcon dusk" Artisan command...
+# Proxy the "dusk" command to the "phalcon dusk" Phalcon command...
 elif [ "$1" == "dusk" ]; then
     shift 1
 
@@ -327,7 +327,7 @@ elif [ "$1" == "dusk" ]; then
         phalcons_is_not_running
     fi
 
-# Proxy the "dusk:fails" command to the "phalcon dusk:fails" Artisan command...
+# Proxy the "dusk:fails" command to the "phalcon dusk:fails" Phalcon command...
 elif [ "$1" == "dusk:fails" ]; then
     shift 1
 
